### ISSUE TITLE
Disk Space Issue : Migrate one image at a time

### ISSUE THREAD

**Issue by ankushagarwal** [docker/migrator#14]
Instead of downloading the entire v1 registry with all images and tags, can we download one at a time and push to the v2 registry? 

The new process would look like : 

1. Query v1 registry for all repositories and their tags
2. Pull one image (with a particular tag) to local docker engine
3. Retag it and push to v2
4. Delete the image from local docker engine
5. Repeat this for all images in v1
 
This addresses the major issue of Disk space on the docker engine host not being sufficient to hold entire v1 registry.

We use S3 for storing our images and all the images cannot fit on a single host's disk.

**Comment by mbentley** [comment]
I've thought about that as a potential way to migrate the images but that only works if you have a v1 registry and a v2 registry using different URLs.  I think it is still a good approach as I agree that needing a disk large enough to hold your entire registry could be very painful.

As a way to work around this, your process makes sense but my hesitation is that you will end up pulling many layers multiple times if a large number of your images have the same base layers.  For example, if you base all of your images on `debian:jessie`, it will pull the base every time since you are removing it every time you pull an image down.  I am not aware of a good way to detect what might be a commonly used base to keep those image layers cached during the pull besides having the user provide what those images might be.

There are a few methods I've also thought about in how to break it up into batches:
1. `n` images to pull, re-tag, and push; then delete all of the images locally
2. Loop through all images in the same namespace before deleting locally
3. Loop through all tags of the same repository before deleting locally
4. Check the local disk space and ensure that X amount of disk space is free before removing the currently cached images locally

I don't love any of these solutions at the moment and am trying to think of a better way to handle large registries.

**Comment by ankushagarwal** [comment]
Thanks. I did not think about the local caching of image layers. I agree that none of 1-4 are ideal, mostly because of DNS switching issue when the URLs are the same, I do like the idea no. 1 though, which is a very simple way of implementing batch migrations.

**Comment by tusharm** [comment]
If we use https://github.com/mrbobbytables/dockproxy, will DNS switching still be a problem?
Although I agree that pulling layers multiple times is a bigger issue.

**Comment by manuelmazzuola** [comment]
I've run in the same issue.
A solution could be to export the ?q= parameter and read it from the env, so, I can migrate group of images

```
IMAGE_LIST="$(curl -s https://${AUTH_CREDS}@${V1_REGISTRY}/v1/search?q=${QUERY_SEARCH:''} | jq -r '.results | .[] | .name')"
```

**Comment by mbentley** [comment]
Ah yes, that would be a great idea to break the chunks into more manageable portions. Thanks!  I'll implement that shortly as an optional parameter.

**Comment by manuelmazzuola** [comment]
:+1:

**Comment by mbentley** [comment]
So I actually decided to go about this slightly differently.  While I think that using the available search filter is good, I think that using `grep` to search allows for greater flexibility due to the ability to use regex.  As far as I can tell, the v1 registry can't handle regex.

**Comment by bobrik** [comment]
Filter is tricky to use. Simpler solution would be splitting image list into chunks of X items. This way you'll have cache locality (base layers are reused to some degree) and limited disk space requirements while the only setting is required: number of images in a chunk.

**Comment by mbentley** [comment]
Unfortunately it really isn't that easy in all cases due to many other
variables in play. The biggest being that you might want to replace a v1
with a v2.  There is a PR that was submitted that runs into that issue and
I was waiting on updates for that before doing anything else around that.

On Sunday, October 18, 2015, Ian Babrou <notifications@github.com> wrote:

> Filter is tricky to use. Simpler solution would be splitting image list
> into chunks of X items. This way you'll have cache locality (base layers
> are reused to some degree) and limited disk space requirements while the
> only setting is required: number of images in a chunk.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/migrator/issues/14#issuecomment-149042169>.
>


-- 
Matt Bentley
Solutions Engineer
Docker, Inc.
317.966.8225

**Comment by mbentley** [comment]
For what it is worth, I do still want to add the ability to migrate images in chunks when the source and destination registries differ.

**Comment by duyanghao** [comment]
This is My solution for this problem.
https://github.com/duyanghao/migrator/tree/Tencent

There are a few methods I've also thought about in how to break it up into batches:
1. n images to pull, re-tag, and push; then delete all of the images locally
2. Loop through all images in the same namespace before deleting locally
3. Loop through all tags of the same repository before deleting locally
4. Check the local disk space and ensure that X amount of disk space is free before removing the currently cached images locally

**I combine the 2 and 4 methods:
Loop through all images in the same namespace before deleting locally under the precondition of 100G amount of free disk space.**
@mbentley @ankushagarwal

**Comment by duyanghao** [comment]
This is my solution for this problem: @ankushagarwal @mbentley 
https://github.com/duyanghao/migrator/tree/Tencent

There are a few methods I've also thought about in how to break it up into batches:
1. n images to pull, re-tag, and push; then delete all of the images locally
2. Loop through all images in the same namespace before deleting locally
3. Loop through all tags of the same repository before deleting locally
4. Check the local disk space and ensure that X amount of disk space is free before removing the currently cached images locally

**I combine the method 2 and 4:
Loop through all images in the same namespace before deleting locally under the precondition of 100G amount of free disk space.**

**Comment by mbentley** [comment]
Added https://github.com/docker/migrator/pull/81 to be able to set the number of images you would like to  pull incrementally.
