### ISSUE TITLE
image tag

### ISSUE THREAD

**Issue by DrDth** [docker/migrator#66]
Hello,

we have a problem with the migration process. When the migraton script pulls the images from the old registry a directory is added. The tags of the images for the new registry contain this added directory. This look something like this: /library/imagename:tag. since its complicated to pull those not correct named images from the new registry it would be nice to change the tag so that they are tagged as image name:tag as usual. Does anyone knows about this "bug" or could tell me where it comes from?

Regards, DrDth

**Comment by mbentley** [comment]
This is because of how the 'official' namespace works (images that do not have a namespace).  Technically, they using the `library` namespace which is how `library` is getting added.  It used to check for that and remove it but this breaks when migrating to Docker Trusted Registry where the official namespace doesn't actually exist.  It could be re-added with a flag to set it as expected; basically adding it back and adding an env var.  See https://github.com/docker/migrator/commit/06f40c9683e64377476bbf0b944c0f07cfebda0b where it was removed.

**Comment by DrDth** [comment]
You don´t have to. I´ll find a solution for myself you don´t need to implement it in the code. but thanks, your answer helped a lot.

regards

**Comment by mbentley** [comment]
I just added a new option to do just this: `LIBRARY_NAMESPACE`
